### ISSUE TITLE
Dependency error with meteorhacks_meteorx  with Meteor 1.8.1 

### ISSUE THREAD

**Issue by tomvolek** [ignacy130/yadmin#7]
HI Ignnacy :  It appears one of the packages you use for yadmin uses old deprecated meterhacks_meteorx which causes crash of Meteor on start up. This is issue is well documented and it is recommended to use a fork of it it which is called lamhieu:meteorx. 

Could you please have yadmin use this package so we can use it going forward ? 
 
/Users/tom/.meteor/packages/meteor-tool/.1.8.1.7c0itz.u7ktr++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190708-20:23:56.391(-7)? (STDERR) 						throw(ex);
W20190708-20:23:56.392(-7)? (STDERR) 						^
W20190708-20:23:56.392(-7)? (STDERR) 
W20190708-20:23:56.392(-7)? (STDERR) TypeError: Cannot read property 'constructor' of undefined
W20190708-20:23:56.392(-7)? (STDERR)     at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
W20190708-20:23:56.392(-7)? (STDERR)     at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
W20190708-20:23:56.392(-7)? (STDERR)     at packages/meteorhacks_meteorx.js:175:1
W20190708-20:23:56.392(-7)? (STDERR)     at packages/meteorhacks_meteorx.js:200:4
W20190708-20:23:56.393(-7)? (STDERR)     at packages/meteorhacks_meteorx.js:208:3
W20190708-20:23:56.393(-7)? (STDERR)     at /Users/tom/Development/payagol/.meteor/local/build/programs/server/boot.js:419:36
W20190708-20:23:56.393(-7)? (STDERR)     at Array.forEach (<anonymous>)
W20190708-20:23:56.393(-7)? (STDERR)     at /Users/tom/Development/payagol/.meteor/local/build/programs/server/boot.js:228:19
W20190708-20:23:56.393(-7)? (STDERR)     at /Users/tom/Development/payagol/.meteor/local/build/programs/server/boot.js:479:5
W20190708-20:23:56.394(-7)? (STDERR)     at Function.run (/Users/tom/Development/payagol/.meteor/local/build/programs/server/profile.js:510:12)
W20190708-20:23:56.394(-7)? (STDERR)     at /Users/tom/Development/payagol/.meteor/local/build/programs/server/boot.js:478:11
=> Exited with code: 1

**Comment by ignacy130** [comment]
Hi, thank you for the info! TBH I don'r develop in meteor no more, but I'll try to update package and publish soon.
